version: '3.1'

services:
  wordpress:
    image: wordpress:${WORDPRESS_VERSION}
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
    networks:
      - mysql
      - traefik
    volumes:
      - wordpress_data:/var/www/html
    deploy:
      labels:
        - traefik.enable=true
        - traefik.constraint-label=traefik
        - traefik.docker.network=traefik
        - traefik.http.services.wordpress.loadbalancer.server.port=80

        # Middlewares
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true

        # Router: HTTP
        - traefik.http.routers.wordpress-http.rule=Host(`${WORDPRESS_HOST}`)
        - traefik.http.routers.wordpress-http.entrypoints=http
        - traefik.http.routers.wordpress-http.middlewares=https-redirect

        # Router: HTTPS
        - traefik.http.routers.wordpress-https.rule=Host(`${WORDPRESS_HOST}`)
        - traefik.http.routers.wordpress-https.entrypoints=https
        - traefik.http.routers.wordpress-https.tls=true
        - traefik.http.routers.wordpress-https.tls.certresolver=le

  mysql:
    image: mysql:${MYSQL_VERSION}
    hostname: mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - mysql
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  mysql:
  traefik:
    external: true

volumes:
  wordpress_data:
  mysql_data:

