version: '3.1'

services:
  wordpress:
    image: wordpress:${WORDPRESS_VERSION}
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    networks:
      - mysql
      - traefik
    volumes:
      - wordpress_data:/var/www/html
    deploy:
      labels:
        traefik.enable: 'true'
        traefik.constraint-label: traefik
        traefik.docker.network: traefik
        traefik.http.services.wordpress.loadbalancer.server.port: 80

        # middlewares
        traefik.http.middlewares.https-redirect.redirectscheme.scheme: https
        traefik.http.middlewares.https-redirect.redirectscheme.permanent: 'true'

        # HTTP router
        traefik.http.routers.wordpress-http.rule: Host(`${WORDPRESS_HOST}`)
        traefik.http.routers.wordpress-http.entrypoints: http
        traefik.http.routers.wordpress-http.middlewares: https-redirect

        # HTTPS router
        traefik.http.routers.wordpress-https.rule: Host(`${WORDPRESS_HOST}`)
        traefik.http.routers.wordpress-https.entrypoints: https
        traefik.http.routers.wordpress-https.tls: 'true'
        traefik.http.routers.wordpress-https.tls.certresolver: le

  mysql:
    image: mysql:${MYSQL_VERSION}
    restart: always
    hostname: mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - mysql
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  mysql:
  traefik:
    external: true

volumes:
  wordpress_data:
  mysql_data:

